do not use include shell script command

diff --git a/src/commands/run_test_plan.yml b/src/commands/run_test_plan.yml
--- a/src/commands/run_test_plan.yml
+++ b/src/commands/run_test_plan.yml
@@ -1,28 +1,54 @@
 description: >
   Runs a test plan on Autify For Mobile.
 parameters:
+  test_plan_api_base_url:
+    type: string
+    default: https://mobile-app.autify.com/api/v1/test_plans/
   test_plan_id:
     type: string
     description: Test Plan ID that you want to run
   build_id:
     type: string
     description: Build ID that you want to run test against
-  test_plan_api_base_url:
-    type: string
-    default: https://mobile-app.autify.com/api/v1/test_plans/
   response_file_path:
     type: string
     default: response-mobile-run-test-plan.txt
     description: File path that keeps the response from the API
 steps:
   - run:
-      name: Setup Secret environment
-      command: |
-        echo "export TEST_PLAN_ID=<<parameters.test_plan_id>>" >> $BASH_ENV
-        echo "export BUILD_ID=<<parameters.build_id>>" >> $BASH_ENV
-  - run:
       name: Run a test plan on Autify For Mobile
-      environment:
-        TEST_PLAN_API_BASE_URL: "<<parameters.test_plan_api_base_url>>"
-        RESPONSE_FILE_PATH: "<<parameters.response_file_path>>"
-      command: <<include(scripts/run_test_plan.sh)>>
+      command: |
+        curl -s -XPOST \
+            -H "Authorization: Bearer ${AUTIFY_FOR_MOBILE_API_TOKEN}" \
+            -H "Content-Type: application/json" \
+            -d "{\"build_id\":\"<<parameters.build_id>>\"}" \
+            "<<parameters.test_plan_api_base_url>>""<<parameters.test_plan_id>>"/test_plan_results \
+            > "<<parameters.response_file_path>>"
+        errors=$(cat "<<parameters.response_file_path>>" | jq .errors)
+        id=$(cat "<<parameters.response_file_path>>" | jq .id)
+        data=$(cat "<<parameters.response_file_path>>" | jq .test_plan)
+        if [ "${errors}" = "null" ]; then
+            if [ "${data}" != "null" ]; then
+                echo "Successfully started the test plan."
+                echo "Test plan name : "$(echo "${data}" | jq -r .name)
+                echo "Build : "$(echo "${data}" | jq -r .build.name)" "$(echo "${data}" | jq -r .build.version)
+                TEST_PLAN_RESULT_ID=${id}
+                echo "Test plan result ID : ${TEST_PLAN_RESULT_ID}"
+            else
+                # In case the response has neither `data` nor `errors`
+                echo "Something went wrong. The response was :"
+                cat "<<parameters.response_file_path>>"
+                exit 1
+            fi
+        else
+            error_messages=$(echo "${errors}" | jq '.[] | .message')
+            echo "Error running the test plan. The error messages are :"
+            if [ "${error_messages}" = "null" ]; then
+                cat "<<parameters.response_file_path>>"
+            else
+                echo "${error_messages}" | while read -r message; do
+                    echo "${message}"
+                done
+            fi
+            exit 1
+        fi
